"""Add Player table

Revision ID: 7c9fdf1afd23
Revises: 86d67cc49172
Create Date: 2025-03-11 13:01:00.089079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9fdf1afd23'
down_revision: Union[str, None] = '86d67cc49172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player'))
    )
    with op.batch_alter_table('shop') as batch_op:
        batch_op.add_column(sa.Column('owned_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(op.f('fk_shop_owned_by_player'), 'player', ['owned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shop_owned_by_player'), 'shop', type_='foreignkey')
    op.drop_constraint(op.f('uq_player_name'), 'player', type_='unique')
    op.drop_column('shop', 'owned_by')
    op.drop_table('player')
    # ### end Alembic commands ###
