"""Add Active Player table

Revision ID: c07c4ea04043
Revises: 7c9fdf1afd23
Create Date: 2025-03-11 13:44:06.956636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07c4ea04043'
down_revision: Union[str, None] = '7c9fdf1afd23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_active_player_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_player'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_player')
    # ### end Alembic commands ###
