"""Add Player money

Revision ID: f92fd0f49d8f
Revises: c07c4ea04043
Create Date: 2025-03-11 14:27:03.672431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92fd0f49d8f'
down_revision: Union[str, None] = 'c07c4ea04043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('money', sa.Integer(), nullable=True))
    with op.batch_alter_table('player') as batch_op:
        batch_op.execute("update player set money = 0")
        batch_op.alter_column('money', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'money')
    # ### end Alembic commands ###
